#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -rf log.*
runApplication renumberMesh -overwrite

#numberOfSubdomains=6
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun
if [ $1 -eq 3 ]|| [ $1 -eq 4 ]|| [ $1 -eq 6 ]
then
    sed -i 's/simpleFoam/SRFSimpleFoam/' system/controlDict
    sed -i 's/pimpleFoam/SRFSimpleFoam/' system/controlDict
else
    sed -i 's/SRFSimpleFoam/simpleFoam/' system/controlDict
    sed -i 's/pimpleFoam/simpleFoam/' system/controlDict
fi
sed -i "s/backward/steadyState/" system/fvSchemes
sed -i "s/runTime/timeStep/" system/controlDict

application=$(getApplication)
runParallel ${application}

runApplication reconstructPar -noFunctionObjects
rm -rf processor*
runApplication foamLog log.${application}
simpleFoam -postProcess -latestTime > log.forces
sed -i 's/SRFSimpleFoam/simpleFoam/' system/controlDict

#------------------------------------------------------------------------------
paraFoam -touch-all