#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runParallel createPatch -overwrite
runApplication reconstructParMesh -constant 
rm -rf processor*


runApplication renumberMesh -overwrite
