#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -rf log.*
runApplication renumberMesh -overwrite
# Meshing in parallel
restore0Dir
#numberOfSubdomains=6
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun

if [ $1 -eq 3 ]|| [ $1 -eq 4 ]
then
    sed -i 's/simpleFoam/SRFSimpleFoam/' system/controlDict
    echo $1
else
    sed -i 's/SRFSimpleFoam/simpleFoam/' system/controlDict
fi
application=$(getApplication)
runParallel ${application}

runApplication reconstructPar -noFunctionObjects
rm -rf processor*
runApplication foamLog log.${application}
sed -i 's/SRFSimpleFoam/simpleFoam/' system/controlDict
#------------------------------------------------------------------------------
paraFoam -touch-all
