#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runParallel createPatch -overwrite
runApplication reconstructParMesh -constant 
rm -rf processor*


runApplication renumberMesh -overwrite

# Meshing in parallel
restore0Dir

#numberOfSubdomains=6
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun

application=$(getApplication)
runParallel ${application} 
runApplication reconstructPar -noFunctionObjects
rm -rf processor*
runApplication foamLog log.${application}
simpleFoam -postProcess -latestTime > log.forces

#------------------------------------------------------------------------------
