#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Meshing in parallel
restore0Dir

#numberOfSubdomains=6
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun
sed -i "s/runTime/timeStep/" system/controlDict
sed -i "s/pimpleFoam/simpleFoam/" system/controlDict
sed -i "s/backward/steadyState/" system/fvSchemes
application=$(getApplication)
runParallel ${application} 

#------------------------------------------------------------------------------
