#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -rf log.*
runApplication renumberMesh -overwrite

#numberOfSubdomains=6
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun

application=$(getApplication)
runParallel ${application}

runApplication reconstructPar -noFunctionObjects
rm -rf processor*
runApplication foamLog log.${application}
simpleFoam -postProcess -latestTime > log.forces
#------------------------------------------------------------------------------
