#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
rm -rf log.*
# cd constant/triSurface/
# for i in $(\ls *.eMesh)
# do
#   surfaceFeatureConvert $i $(echo $i | sed -e 's/eMesh/vtk/')
# done
# cd -
# Meshing in parallel
#---------------------
runApplication blockMesh

#numberOfSubdomains=4
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParMesh

runParallel snappyHexMesh -overwrite
cat processor0/constant/polyMesh/boundary | grep air_to_sphere > patch_list.txt

# Running in parallel
#---------------------

