#!/bin/sh
#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
# Meshing in parallel
#---------------------
mv system/blockMeshDict.$1 system/blockMeshDict
runApplication blockMesh
mv system/blockMeshDict system/blockMeshDict.$1
#numberOfSubdomains=4
#sed -i 's/^numberOfSubdomains.*/numberOfSubdomains '$numberOfSubdomains';/' system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParMesh

runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant
rm -rf processor*
runApplication topoSet
runApplication createPatch -overwrite
runApplication renumberMesh -overwrite

# snappyHexMesh -overwrite

# cd constant/triSurface/
# for i in $(\ls *.eMesh)
# do
#   surfaceFeatureConvert $i $(echo $i | sed -e 's/eMesh/vtk/')
# done
# cd -

# Running in parallel
#---------------------

